.docker_stages:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login ${CI_REGISTRY} -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
  after_script:
    - docker logout ${CI_REGISTRY}

stages:
  - build
  - deploy

Production Build:
  extends: .docker_stages
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  stage: build
  only:
    - production
  tags:
    - gitlab-org-docker 
  script:
    - >
      docker build
      --pull
      --build-arg VCS_REF=${CI_COMMIT_SHA}
      --build-arg VCS_URL=${CI_PROJECT_URL}
      --tag ${CI_REGISTRY_IMAGE}:git-${CI_COMMIT_SHORT_SHA}
      --file Dockerfile
      .
    - docker push ${CI_REGISTRY_IMAGE}:git-${CI_COMMIT_SHORT_SHA}

Lab Build:
  extends: .docker_stages
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  stage: build
  only:
    - labdev
  script:
    - >
      docker build
      --pull
      --build-arg VCS_REF=${CI_COMMIT_SHA}
      --build-arg VCS_URL=${CI_PROJECT_URL}
      --tag ${CI_REGISTRY_IMAGE}:git-${CI_COMMIT_SHORT_SHA}
      --file Dockerfile
      .
    - docker push ${CI_REGISTRY_IMAGE}:git-${CI_COMMIT_SHORT_SHA}

Deployment:
  stage: deploy
  image: registry.gitlab.com/rambleon/kustomize-image:latest
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config --global user.name "GitLab Runner"
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - git config --list
    - git clone --recurse-submodules -j8 git@gitlab.com:rambleon/kas-deploy.git /tmp/kas-deploy
    - pushd .
    - cd deploy/overlays/production
    - kustomize edit set image registry.gitlab.com/rambleon/rambleon-org=registry.gitlab.com/rambleon/rambleon-org:git-${CI_COMMIT_SHORT_SHA}
    - popd
    - kustomize build deploy/overlays/production > /tmp/kas-deploy/rambleonorg.yml
    - cd /tmp/kas-deploy
    - git add rambleonorg.yml
    - git commit -m "Updated rambleon.org manifest" || echo "No changes, nothing to commit!"
    - git push origin main
  tags:
    - gitlab-org-docker 
